# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e3e05731d459af1b7af4bab4c5d45f5b83d4b5d1f6c1fc58ecd2a63f61e06e986ac129befb9ba5046b35530fac6e4f2228697251398b874ec0d708d0b40d34f

test:
  secret_key_base: 388f389e3e10a8b43f2d6f51215c0492048d0729e2eb983d0bcbdaed22a293421b61cb65dd0571a019429bf7792685796a3932ca144a9bbb1bd2ee3fb8bd2c11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
